package com.accessplus.eventpro.core.security;

import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.security.web.csrf.CsrfTokenRepository;

/**
 * Remembers the raw token loaded or generated during the current request.
 *
 * <p>This lets the explicit token endpoint reuse a token eagerly generated by
 * Spring's SPA request handler instead of emitting a second Set-Cookie header.</p>
 */
public final class RequestCachingCsrfTokenRepository implements CsrfTokenRepository {

    private static final String CURRENT_TOKEN_ATTRIBUTE =
            RequestCachingCsrfTokenRepository.class.getName() + ".CURRENT_TOKEN";

    private final CsrfTokenRepository delegate;

    public RequestCachingCsrfTokenRepository(CsrfTokenRepository delegate) {
        this.delegate = delegate;
    }

    @Override
    public CsrfToken generateToken(HttpServletRequest request) {
        CsrfToken token = delegate.generateToken(request);
        remember(request, token);
        return token;
    }

    @Override
    public void saveToken(CsrfToken token, HttpServletRequest request, HttpServletResponse response) {
        if (token == null) {
            request.removeAttribute(CURRENT_TOKEN_ATTRIBUTE);
        } else {
            remember(request, token);
        }
        delegate.saveToken(token, request, response);
    }

    @Override
    public CsrfToken loadToken(HttpServletRequest request) {
        CsrfToken token = delegate.loadToken(request);
        if (token != null) {
            remember(request, token);
        }
        return token;
    }

    public static CsrfToken currentToken(HttpServletRequest request) {
        Object token = request.getAttribute(CURRENT_TOKEN_ATTRIBUTE);
        return token instanceof CsrfToken csrfToken ? csrfToken : null;
    }

    private static void remember(HttpServletRequest request, CsrfToken token) {
        request.setAttribute(CURRENT_TOKEN_ATTRIBUTE, token);
    }
}
